- hosts: localhost
  become: true
  # pre_tasks:
  #   - name: atualizar repositórios
  #     apt: update_cache=yes
  #     changed_when: False

  tasks:
    # - include: tasks/packages.yml
    # - include: tasks/adding_user_to_group.yaml
    - include: tasks/removing_user_from_groups.yaml
    # - include: tasks/cron.yml  