- name: create ansible user
  user: 
    name: ansible-user
    password: secret
    uid: 900
    group: 
      - docker
      - sudo
    state: present
    shell: /bin/bash       # Defaults to /bin/bash
    system: no             # Defaults to no
    createhome: yes        # Defaults to yes
    home: /home/ansible    # Defaults to /home/<username>






# - name: copy sudoers_ansible
#   copy: src=files/sudoers_ansible dest=/etc/sudoers.d/ansible owner=root group=root mode=0440

  # user: root
  # vars:
  #   # created with:
  #   # python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'
  #   password: $1$SomeSalt$UqddPX3r4kH3UL5jq5/ZI.
  #   tasks:
  #   - user: name=tset password={{password}}