# Generated by Django 3.1.4 on 2020-12-15 00:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exemploxpto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20, verbose_name='descricao')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'exemploxpto',
                'verbose_name_plural': 'exemplosxpto',
            },
        ),
    ]
